version: '3'
services:
  nginx:
    container_name: spa_nginx
    build: ./nginx
    ports:
      - '9000:80'
    volumes:
      - ./vue/vueproject:/var/www/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params

  vue:
    container_name: spa_vue
    build: ./vue
    volumes:
      - ./vue/vueproject:/app
    tty: true
    ports:
      - '8080:8080'

  django:
    container_name: spa_django
    build: ./django
    volumes:
      - ./django/code:/code
    tty: true
    ports:
      - '8000:8000'
