version: '3'

volumes:
  db-volumes:
    driver: local

services:
  nginx:
    container_name: spa_nginx
    build: ./nginx
    ports:
      - '9000:80'
    volumes:
      - ./vue/vueproject:/var/www/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params

  vue:
    container_name: spa_vue
    build: ./vue
    volumes:
      - ./vue/vueproject:/app
    tty: true
    ports:
      - '8080:8080'

  django:
    container_name: spa_django
    build: ./django
    command: python djangoproject/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django/code:/code
    tty: true
    ports:
      - '8000:8000'
    depends_on:
      - postgres

  postgres:
    container_name: spa_postgres
    build: ./postgres
    ports:
      - '5432:5432'
    volumes:
      - db-volumes:/var/lib/postgresql/data
